(* =========================================================================
   reflectsem/export_functions.sml — emit candle defines for the FULL
   function cone of CakeML's evaluate: direct functions printed from their
   original defining theorems; recursion HOL Light cannot take printed from
   the fueled mirrors (fueledSemTheory, generated by fueledGenLib).

   Run on a host with the built CakeML semantics and a built fueledSemTheory
   (Holmake in reflectsem/), in $CAKEMLDIR/semantics:
     cd $CAKEMLDIR/semantics && \
       $HOLDIR/bin/hol < $SVENVS_ROOT/reflectsem/export_functions.sml
   Output: $REFLECTSEM_OUT_DIR/reflectsem_functions.ml, default directory
   ${TMPDIR:-/tmp}/svenvs-$USER (the path written is printed; submit after
   reflectsem_datatypes.ml)
   ========================================================================= *)

val () = print "=== export_functions: loading ===\n";

(* output directory: $REFLECTSEM_OUT_DIR, default ${TMPDIR:-/tmp}/svenvs-$USER *)
val out_dir =
  case OS.Process.getEnv "REFLECTSEM_OUT_DIR" of
    SOME d => d
  | NONE =>
      let val tmp = case OS.Process.getEnv "TMPDIR" of
                      SOME t => t | NONE => "/tmp"
          val user = case OS.Process.getEnv "USER" of
                       SOME u => u | NONE => "unknown"
      in OS.Path.concat (tmp, "svenvs-" ^ user) end;
val () =
  if OS.FileSys.access (out_dir, []) then ()
  else OS.FileSys.mkDir out_dir;
val out_path = OS.Path.concat (out_dir, "reflectsem_functions.ml");
val cakemldir =
  case OS.Process.getEnv "CAKEMLDIR" of
    SOME d => d
  | NONE => OS.Path.concat (valOf (OS.Process.getEnv "HOME"), "dev/CakeML");
val svenvs =
  case OS.Process.getEnv "SVENVS_ROOT" of
    SOME d => d
  | NONE => OS.Path.concat (valOf (OS.Process.getEnv "HOME"), "dev/svenvs");
val () = loadPath :=
  map (fn d => OS.Path.concat (cakemldir, d))
      ["semantics", "semantics/ffi", "misc", "basis/pure"]
  @ [OS.Path.concat (svenvs, "reflectsem")] @ !loadPath;
val () = load "fueledSemTheory";
val () = use (OS.Path.concat (svenvs, "reflectsem/exportLib.sml"));

open HolKernel boolLib;

(* same monomorphization as the datatype phase *)
local
  val mlstring_ty = mk_thy_type {Thy="mlstring", Tyop="mlstring", Args=[]}
  fun spec_for ty keepers =
    let val {Args,...} = dest_thy_type ty
    in map (fn a => if Lib.mem (dest_vartype a) keepers then NONE
                    else SOME mlstring_ty) Args
    end
  val ns_ty = let val SOME tyi = TypeBase.read {Thy="namespace",Tyop="namespace"}
              in TypeBasePure.ty_of tyi end
  val id_ty = let val SOME tyi = TypeBase.read {Thy="namespace",Tyop="id"}
              in TypeBasePure.ty_of tyi end
in
val () = exportLib.mono_tab :=
  [(("namespace","namespace"), spec_for ns_ty ["'v"]),
   (("namespace","id"),        spec_for id_ty [])]
end;

(* ---------------- classification ---------------- *)

(* originals replaced by fueled mirrors (printed from fueledSemTheory) *)
val fueled_members =
  [("ast","pat_bindings"), ("ast","pats_bindings"),
   ("ast","every_exp"),
   ("semanticPrimitives","one_con_check"),
   ("semanticPrimitives","do_eq"), ("semanticPrimitives","do_eq_list"),
   ("semanticPrimitives","pmatch"), ("semanticPrimitives","pmatch_list"),
   ("semanticPrimitives","v_to_list"),
   ("semanticPrimitives","v_to_char_list"),
   ("semanticPrimitives","vs_to_string"),
   ("semanticPrimitives","concrete_v"),
   ("semanticPrimitives","concrete_v_list"),
   ("semanticPrimitives","can_pmatch_all"),
   ("semanticPrimitives","do_test"),
   ("semanticPrimitives","v_to_word8_list"),
   ("semanticPrimitives","v_to_word64_list"),
   ("semanticPrimitives","compiler_agrees"),
   ("semanticPrimitives","do_app"),
   ("semanticPrimitives","do_eval"),
   ("evaluate","do_eval_res"),
   ("evaluate","evaluate"), ("evaluate","evaluate_match"),
   ("evaluate","evaluate_decs")];

(* the fueled defs, in dependency order, as stored in fueledSemTheory *)
val fueled_defs =
  ["pat_bindings_n_def", "every_exp_n_def", "one_con_check_n_def",
   "do_eq_n_def", "pmatch_n_def", "v_to_list_n_def", "v_to_char_list_n_def",
   "vs_to_string_n_def", "concrete_v_n_def", "can_pmatch_all_n_def",
   "do_test_n_def", "v_to_word8_list_n_def", "v_to_word64_list_n_def",
   "compiler_agrees_n_def", "do_app_n_def", "do_eval_n_def", "do_eval_res_n_def", "eval_n_def"];

(* theories whose constants are builtins/opaques/prelude — never exported *)
val skip_thys =
  ["min","bool","pair","num","prim_rec","arithmetic","list","rich_list",
   "alist","option","sum","one","combin","string","integer","words","fcp",
   "binary_ieee","machine_ieee","fpSem","integer_word","ternaryComparisons",
   "while","ind_type","relation","sat","marker","normalForms","pred_set",
   "divides","numeral","basicSize","bit","logroot","numposrep","ASCIInumbers"];

(* extra prelude functions exported from their HOL4 defining theorems *)
val prelude_funs : (string * thm) list = [
  ("cml_TAKE",        listTheory.TAKE_def),
  ("cml_DROP",        listTheory.DROP_def),
  ("cml_FLAT",        listTheory.FLAT),
  ("cml_FOLDR",       listTheory.FOLDR),
  ("cml_ZIP",         listTheory.ZIP_def),
  ("cml_LUPDATE",     listTheory.LUPDATE_def),
  ("cml_oEL",         listTheory.oEL_def),
  ("cml_ALL_DISTINCT",listTheory.ALL_DISTINCT),
  ("cml_ALOOKUP",     alistTheory.ALOOKUP_def),
  ("cml_EL",          listTheory.EL),
  ("cml_Num",         integerTheory.Num),
  ("cml_int_div",     integerTheory.int_div),
  ("cml_int_mod",     integerTheory.int_mod)
];

(* ---------------- the function walk (topological) ---------------- *)

structure SS = Redblackset;
fun spcmp ((a,b),(c,d)) =
  case String.compare (a,c) of EQUAL => String.compare (b,d) | x => x;
val seen = ref (SS.empty spcmp);
val order = ref ([] : ((string * string) * thm) list);  (* direct exports *)
val missing = ref ([] : (string * string) list);

fun try_fetch thy nm = SOME (DB.fetch thy nm) handle HOL_ERR _ => NONE;
fun defthm (thy,name) =
  case try_fetch thy (name ^ "_def") of SOME th => SOME th | NONE =>
  case try_fetch thy (name ^ "_DEF") of SOME th => SOME th | NONE =>
  try_fetch thy name;

(* datatype-derived constants (constructors/cases/accessors/fupds) need no
   function export — they came with the datatype phase *)
fun is_dt_derived c =
  let
    val ty = let val (_,rng) = strip_fun (type_of c) in rng end
  in
    (case TypeBase.fetch ty of
       SOME _ =>
         (List.exists (fn k => Term.same_const c k)
            (TypeBase.constructors_of ty)
          handle HOL_ERR _ => false)
     | NONE => false)
    orelse
    let val {Name,...} = dest_thy_const c
    in String.isSubstring "_CASE" Name orelse
       String.isSubstring "recordtype" Name orelse
       String.isSubstring "_fupd" Name
    end
  end;

fun visit c =
  let
    val {Thy,Name,...} = dest_thy_const c
    val k = (Thy,Name)
  in
    if SS.member (!seen, k) then ()
    else if Lib.mem Thy skip_thys then seen := SS.add (!seen, k)
    else if Lib.mem k fueled_members then seen := SS.add (!seen, k)
    (* the mirrors themselves are emitted once, by the fueled section below *)
    else if Thy = "fueledSem" then seen := SS.add (!seen, k)
    else if is_dt_derived c then seen := SS.add (!seen, k)
    else
      (seen := SS.add (!seen, k);
       case defthm k of
         NONE => missing := k :: !missing
       | SOME th =>
         let
           val heads =
             List.mapPartial
               (fn cj => Lib.total (fn () =>
                   let val (l,_) = dest_eq (snd (strip_forall cj))
                   in fst (strip_comb l) end) ())
               (strip_conj (concl th))
           val () = List.app (fn h =>
               if is_const h then
                 let val {Thy=t,Name=n,...} = dest_thy_const h
                 in seen := SS.add (!seen, (t,n)) end
               else ()) heads
           val () = List.app visit
               (List.filter is_const (find_terms is_const (concl th)))
         in order := (k, th) :: !order end)
  end;

(* seed with everything the FUELED defs reference (the fueled bodies are
   what ends up in candle, so their callees define the needed direct set) *)
val () = List.app
  (fn d =>
     List.app visit
       (List.filter is_const
          (find_terms is_const (concl (DB.fetch "fueledSem" d)))))
  fueled_defs;

val direct = List.rev (!order);
val () = print ("direct functions: " ^ Int.toString (length direct) ^ "\n");
val () = List.app (fn (t,n) => print ("MISSING def: " ^ t ^ "$" ^ n ^ "\n"))
                  (!missing);

(* ---------------- emit ---------------- *)

val buf = ref ([] : string list);
fun emit s = buf := s :: !buf;

val () = emit "(* GENERATED by svenvs reflectsem/export_functions.sml — the";
val () = emit "   function cone of CakeML's evaluate. Direct functions printed";
val () = emit "   from their HOL4 defining theorems; fueled mirrors printed from";
val () = emit "   fueledSemTheory (see fueledGenLib.sml). Load AFTER";
val () = emit "   reflectsem_datatypes.ml. Do not edit by hand. *)";
val () = emit "";
val () = emit "(* -- compiled-pattern scaffolding (HOL4 case/std combinators) -- *)";
val () = emit "let cml_K_def = define `cml_K x y = x`;;";
val () = emit "let cml_S_def = define `cml_S f g x = (f x) (g x)`;;";
val () = emit "let cml_C_def = define `cml_C f x y = f y x`;;";
val () = emit "let cml_W_def = define `cml_W f x = f x x`;;";
val () = emit "let cml_literal_case_def = define `cml_literal_case f x = f x`;;";
val () = emit "let cml_num_CASE_def = define \
              \`cml_num_CASE n b f = if n = 0 then b else f (PRE n)`;;";
val () = emit "let list_CASE_def = define \
              \`(list_CASE [] v f = v) /\\ (list_CASE (CONS h t) v f = f h t)`;;";
val () = emit "let option_CASE_def = define \
              \`(option_CASE NONE v f = v) /\\ (option_CASE (SOME x) v f = f x)`;;";
val () = emit "let sum_CASE_def = define \
              \`(sum_CASE (INL x) f g = f x) /\\ (sum_CASE (INR y) f g = g y)`;;";
val () = emit "let pair_CASE_def = define `pair_CASE p f = f (FST p) (SND p)`;;";
val () = emit "";
val () = emit "(* -- list/alist helpers (printed from HOL4 defining theorems) -- *)";
val () = List.app
  (fn (nm, th) =>
     emit (exportLib.pdefine_named (nm ^ "_def")
             (map exportLib.total_clause (strip_conj (concl th))))
     handle e => emit ("(* FAILED prelude " ^ nm ^ " : "
                       ^ General.exnMessage e ^ " *)"))
  prelude_funs;
val () = emit "";
val () = emit "(* ---- direct functions (dependency order) ---- *)";
val () = List.app
  (fn ((thy,nm), th) =>
     (emit ("(* " ^ thy ^ "$" ^ nm ^ " *)");
      emit (exportLib.pdefine_smart (exportLib.rename nm ^ "_def")
              (map exportLib.total_clause (strip_conj (concl th)))))
     handle e => emit ("(* FAILED " ^ thy ^ "$" ^ nm ^ " : "
                       ^ General.exnMessage e ^ " *)"))
  direct;
val () = emit "";
val () = emit "(* ---- fueled mirrors (from fueledSemTheory) ---- *)";
val () = List.app
  (fn d =>
     (emit ("(* fueledSem$" ^ d ^ " *)");
      emit (exportLib.pdefine_smart d
              (map exportLib.total_clause
                   (strip_conj (concl (DB.fetch "fueledSem" d))))))
     handle e => emit ("(* FAILED fueled " ^ d ^ " : "
                       ^ General.exnMessage e ^ " *)"))
  fueled_defs;
(* the rewrite base for evaluating the ported semantics by rewriting:
   every scaffolding/prelude definition and every rewrite-safe clause
   theorem, as ONE list the gate scripts use (no guessing names) *)
val () = emit ("let reflectsem_fn_thms = [" ^ String.concatWith "; "
  (["cml_K_def", "cml_S_def", "cml_C_def", "cml_W_def", "cml_literal_case_def",
    "cml_num_CASE_def", "list_CASE_def", "option_CASE_def", "sum_CASE_def",
    "pair_CASE_def"]
   @ map (fn (nm, _) => nm ^ "_def") prelude_funs
   @ List.rev (!exportLib.rewrite_safe)) ^ "];;");
val () = emit "let REFLECTSEM_FUNCTIONS_END = 1;;";

(* prelude of opaque declarations collected during printing *)
val out = TextIO.openOut out_path;
val () = TextIO.output (out,
  "(* opaque leaf types/operations: meaning pinned by the HOL4 bridge *)\n\
  \new_type (\"rounding\", 0);;\n");
val () = List.app
  (fn (nm, ty) =>
     TextIO.output (out, "new_constant (\"" ^ nm ^ "\", `:" ^ ty ^ "`);;\n"))
  (List.rev (!exportLib.opaque_seen));
val () = List.app (fn s => TextIO.output (out, s ^ "\n")) (List.rev (!buf));
val () = TextIO.closeOut out;
val () = print ("wrote " ^ out_path ^ "\n");

(* ---------------- loud checks: nothing printed may be undefined -------- *)
val fail_count = ref 0;
fun fail_msg s = (print ("EXPORT_FAIL " ^ s ^ "\n"); fail_count := !fail_count + 1);

(* every cml_* builtin target must be defined by scaffolding/prelude/opaques *)
val scaffold_cml = ["cml_K","cml_S","cml_C","cml_W","cml_literal_case",
                    "cml_num_CASE","cml_CHR","cml_ORD","cml_char_lt"];
val () = List.app
  (fn n => if Lib.mem n scaffold_cml
              orelse List.exists (fn (p,_) => p = n) prelude_funs
              orelse List.exists (fn (p,_) => p = n) (!exportLib.opaque_seen)
           then () else fail_msg ("builtin target never defined: " ^ n))
  (!exportLib.cml_used);
(* no builtin-theory constant may fall through to its bare name *)
val () = List.app
  (fn (t,n) => fail_msg ("unmapped builtin constant: " ^ t ^ "$" ^ n))
  (!exportLib.unmapped_seen);
(* every in-text failure marker counts *)
val () = List.app
  (fn s => if String.isSubstring "FAILED" s then fail_msg s else ())
  (!buf);
(* every datatype the printed functions mention must have been exported by
   export_datatypes.sml (its manifest), or be a candle builtin/opaque *)
val manifest_path = OS.Path.concat (out_dir, "reflectsem_datatypes.manifest");
val manifest =
  let val ins = TextIO.openIn manifest_path
      fun loop acc = case TextIO.inputLine ins of
                       NONE => (TextIO.closeIn ins; acc)
                     | SOME l => loop (String.tokens Char.isSpace l @ acc)
  in loop [] end
  handle _ => (fail_msg ("no datatype manifest at " ^ manifest_path ^
                         " (run export_datatypes.sml first)"); []);
val builtin_tys =
  ["min$bool","min$fun","num$num","integer$int","list$list","option$option",
   "pair$prod","sum$sum","one$one","string$char","words$word","fcp$bit0",
   "fcp$bit1","one$one","min$ind","fpSem$rounding","binary_ieee$rounding"];
fun check_ty ty =
  if is_vartype ty then ()
  else let val {Thy,Tyop,Args} = dest_thy_type ty
           val k = Thy ^ "$" ^ Tyop
       in if exportLib.is_word8 ty orelse exportLib.is_word64 ty then ()
          else (if Lib.mem k builtin_tys orelse Lib.mem k manifest then ()
                else fail_msg ("datatype not exported: " ^ k);
                List.app check_ty Args)
       end;
local
  val seen = ref ([] : string list)
  fun tys_of th =
    List.app (fn t => check_ty (type_of t))
      (find_terms (fn t => is_const t orelse is_var t) (concl th))
in
val () = List.app (fn (_,th) => tys_of th) prelude_funs;
val () = List.app (fn (_,th) => tys_of th) direct;
val () = List.app (fn d => tys_of (DB.fetch "fueledSem" d)) fueled_defs;
end;
val () = List.app (fn (n, r) => print ("ROUTE " ^ n ^ " : " ^ r ^ "\n"))
                  (List.rev (!exportLib.smart_log));
val () =
  if !fail_count = 0 then print "EXPORT_FUNCTIONS_OK\n"
  else (print ("EXPORT_FUNCTIONS_FAILED (" ^ Int.toString (!fail_count) ^
               " problems)\n");
        OS.Process.exit OS.Process.failure);
