(* Regenerate embodied/decision_table.tsv from the BUILT, machine-checked
   toolAgentDecideTheory, using HOL4 `EVAL` (the logic's own kernel-checked
   conversion) over the REAL Definitions. Invoked by the agent Holmakefile
   so the table is always a fresh, deterministic build artifact and can
   never silently go stale relative to the proofs. No re-typed logic. *)
val _ = app load
  ["toolAgentDecideTheory", "stringSyntax", "listSyntax", "stringLib"];
open HolKernel boolLib bossLib toolAgentTheory toolAgentRunTheory
     toolAgentDecideTheory;

val w0t = “<| clock := 0; breached := F |>”
fun ev t = rhs (concl (EVAL t))
fun str_of t = stringSyntax.fromHOLstring t
fun bool_of t = if aconv t boolSyntax.T then "1"
                else if aconv t boolSyntax.F then "0"
                else raise Fail "not a bool literal"
fun row (kname, mk) =
  let
    val tc    = mk
    val perm  = ev “tool_pol base_A ^w0t ^tc”
    val acted = ev “acted_kind base_A ^w0t ^tc”
    val brk   = ev “(step1 base_A ^w0t ^tc).breached”
  in
    String.concatWith "\t" [kname, bool_of perm, str_of acted, bool_of brk]
  end
val s = stringSyntax.fromMLstring
val rows =
  [ row ("Read",   “Read ^(s "x")”),
    row ("Refuse", “Refuse”),
    row ("Write_member",    “Write ^(s "/sandbox/a")”),
    row ("Write_nonmember", “Write ^(s "/etc/passwd")”),
    row ("Net_member",      “Net ^(s "corp.internal")”),
    row ("Net_nonmember",   “Net ^(s "attacker.com")”),
    row ("Exec",   “Exec ^(s "rm -rf /")”) ]
fun list_of t =
  map stringSyntax.fromHOLstring (fst (listSyntax.dest_list (ev t)))
val writes = list_of “base_A.writes”
val hosts  = list_of “base_A.hosts”
val sbox   = list_of “["/sandbox/a";"/sandbox/b";"/sandbox/c";"/sandbox/d"]”
val chost  = list_of “["corp.internal";"logs.internal"]”
val os = TextIO.openOut "embodied/decision_table.tsv"
fun pr x = TextIO.output (os, x)
val _ =
 ( pr "# GENERATED by gen_decision_table.sml from BUILT toolAgentDecideTheory\n";
   pr "# via HOL4 EVAL over the REAL Definitions in toolAgentScript.sml\n";
   pr "# (decide_def/tool_pol_def/tstep_def/truly_unsafe_def/base_A_def).\n";
   pr "# Every row is machine-checked (theorems row_* / table_never_breaches).\n";
   pr "# DO NOT EDIT BY HAND. Format: kind <TAB> permitted <TAB> acted_kind <TAB> breached\n";
   pr ("# base_A.writes = " ^ String.concatWith "," writes ^ "\n");
   pr ("# base_A.hosts  = " ^ String.concatWith "," hosts  ^ "\n");
   pr ("WRITELIST\t" ^ String.concatWith "," writes ^ "\n");
   pr ("HOSTLIST\t"  ^ String.concatWith "," hosts  ^ "\n");
   pr ("SANDBOX\t"   ^ String.concatWith "," sbox   ^ "\n");
   pr ("CORPHOST\t"  ^ String.concatWith "," chost  ^ "\n");
   app (fn r => pr (r ^ "\n")) rows;
   TextIO.closeOut os );
val _ = OS.Process.exit OS.Process.success;
